### 
GET http://localhost:1234


### RECUPERAR TODAS LAS PELICULAS
GET http://localhost:1234/movies

### RECUPERAR UNA PELICULA POR EL ID
GET http://localhost:1234/movies/1

### RECUPERAR TODAS LAS PELICULAS POR UN GENERO
GET http://localhost:1234movies?genre= terror