### 
GET http://localhost:1234


### RECUPERAR TODAS LAS PELICULAS
GET http://localhost:1234/movies

### RECUPERAR UNA PELICULA POR EL ID
GET http://localhost:1234/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf

### RECUPERAR TODAS LAS PELICULAS POR UN GENERO
GET http://localhost:1234/movies?genre=Adventure

### CREAR UNA PELICULA
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "The Shawshank Redemption",
    "year": 1950,
    "director": "Frank Darabont",
    "duration": 142,
    "poster": "https://i.ebayimg.com/images/g/4goAAOSwMyBe7hnQ/s-l1200.webp",
    "genre": [
      "Drama"
    ],
    "rate": 9.3
}
